name: fluttguitar
description: A new Flutter project for a guitar shop.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.8.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  flutter_map: 0.10.1+1 
  geolocator: ^5.3.1
  latlong: ^0.6.1
  auto_size_text: ^2.1.0
  provider: 4.3.2+3
  shared_preferences: ^0.5.3+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - lib/images/


  
